name: artiste-peintre CI

on:
  push:
    branches:
      - 'chore/**'
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
      - 'test/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Build Project
        run: |
          pnpm install
          pnpm build

      # - name: Test Project
      #   run: pnpm test
